#' @title Convert Parameters
#'
#' takes list of parameters as generated by parameters() function and converts all rates and day parameters to specified timestep
#'
#' @param parms list of parameters generated inside parameters()
#'
#' @return
#' list of parameters to be used in covid_19_main_function
#'
#' @export
convert_parms <- function(parms) {

  parms$n_days_rec_ICU = parms$n_days_rec_ICU / parms$timestep
  parms$exposed_transition_rate = parms$exposed_transition_rate * parms$timestep
  parms$infected_transition_rate = parms$infected_transition_rate * parms$timestep
  parms$n_days_rec_hosp = parms$n_days_rec_hosp / parms$timestep
  parms$mixing_matrix = parms$mixing_matrix * parms$timestep

  return(parms)
}
